[package]
name = "discord_message_scheduler_bot"
version = "0.1.0"
edition = "2024"
authors = ["beanbeanjuice"]

[dependencies]
chrono = "0.4.41"
dotenv = "0.15.0"
parse_duration = "2.1.1"
poise = "0.6.1"
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
